### ISSUE TITLE
El enlace a Slides no funciona. Da 404

### ISSUE THREAD

**Issue by antoniogarcia78** [asanzdiego/curso-git-github-markdown-2016#1]
El enlace a Slides no funciona. Da 404
Apunta a http://www.slideshare.net/asanzdiego/git-github-y-markdown-2016
y en slideshare existe http://www.slideshare.net/asanzdiego/git-github-y-markdown

Me estoy adelantado a la subida a slideshare?

**Comment by asanzdiego** [comment]
Gracias por la issue. Efectivamente te has adelantado -__^
